# Generated by Django 5.0.2 on 2024-02-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicii', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicii',
            new_name='ServiciiModel',
        ),
    ]
